src/menu/urls.py
from django.urls import path
from .views import menu_view,add_menu_view,edit_menu_view

app_name='menu'

urlpatterns = [
#   path('', index, name='index'),
   path('', menu_view, name='list'),
    path('addm/', add_menu_view, name='add'),
    path('editm/<int:id>/', edit_menu_view, name='edit'),
    
]

src/plat/urls.py
from django.urls import path
from .views import plat_view,add_plat_view,edit_plat_view

app_name='plat'

urlpatterns = [
   path('plat/', plat_view, name='list'),
    path('addp/', add_plat_view, name='add'),
    path('editp/<int:id>/', edit_plat_view, name='edit'),
    
]

src/src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("menu.urls")),
    path('plat/',include("plat.urls")),
]

src/dashboard/models.py
from django.db import models

# Create your models here.

src/menu/models.py
from django.db import models
from plat.models import PlatModel

class MenuModel(models.Model):
    plat = models.OneToOneField(PlatModel, on_delete=models.CASCADE, null=True, blank=True)  
    creation_date = models.DateField(auto_now_add=True)  

    def __str__(self):
        return self.creation_date 

src/plat/models.py
from django.db import models

class PlatModel(models.Model):
    name = models.CharField(max_length=100)  
    summary = models.TextField()  

    def __str__(self):
        return self.name 

src/menu/forms.py
from django import forms
from .models import MenuModel

class MenuForm(forms.ModelForm):
    class Meta:
        model = MenuModel
        fields = ['plat'] 

src/plat/forms.py
from django import forms
from menu.models import PlatModel


class PlatForm(forms.ModelForm):
 class Meta:
    model= PlatModel
    fields=["name","summary"]
   

src/dashboard/views.py
from django.shortcuts import render

# Create your views here.

src/menu/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from menu.models import MenuModel
from .forms import MenuForm
from plat.forms import PlatForm



# Create your views here.

#def index(request):
#    return render(request,'menu/index.html')  


def menu_view(request):
    return render(request,'menu/menus.html')  


def edit_menu_view(request, id):  
    menus = get_object_or_404(MenuModel, id=id)  
    
    if request.method == 'POST':

        form = MenuForm(request.POST, instance=menus)  
        if form.is_valid():
            form.save()  
            return redirect('menu:list') 
    else:
        form = UserForm(instance=menus) 
    context["form"] = form
    
    return render(request, 'menu/edit_form.html', context)



        

def add_menu_view(request):
    if request.method == "POST":
        menu_form = MenuForm(request.POST)
        plat_form = PlatForm(request.POST)

        if menu_form.is_valid() and plat_form.is_valid():
            plat_form = plat_form.save()
            menus = menu_form.save(commit=False)
            menus.plats = plat_form 
            menus.save()

            messages.success(request, 'menu added successfully!')
            return redirect('menus:list')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        menu_form = UserForm()
        plat_form = PlatForm()

    return render(request, 'html/forms.html', {'menu_form': menu_form, 'plat_form': plat_form})

src/plat/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from plat.models import PlatModel
from menu.forms import MenuForm
from .forms import PlatForm



# Create your views here.



def plat_view(request):
    return render(request,'plat/plats.html')  
#   search_field = request.GET.get('search')
#    if search_field :
 #       menus = UserModel.objects.filter(plat__icontains=search_field)
 #       context = {
 #           'menus': menus,
 #           'search_field': search_field,
  #      }
#    else:
#        menus = MenuModel.objects.all() 
#        context = {
#            'menus': menus,
#        }
#    return render(request, 'html/menus.html',context)


def edit_plat_view(request, id):  
    plats = get_object_or_404(PlatModel, id=id)  
    
    if request.method == 'POST':

        form = PlatForm(request.POST, instance=plats)  
        if form.is_valid():
            form.save()  
            return redirect('plat:list') 
    else:
        form = PlatForm(instance=plats) 
    context["form"] = form
    
    return render(request, 'plat/edit_form.html', context)



        

def add_plat_view(request):
    if request.method == "POST":
        plat_form = PlatForm(request.POST)

        if menu_form.is_valid() and plat_form.is_valid():
            plat_form = plat_form.save()
            plat_form.save()

            messages.success(request, 'plat added successfully!')
            return redirect('plat:list')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        plat_form = PlatForm()

    return render(request, 'html/forms.html', {'plat_form': plat_form})

src/templates/base.html
{%load static%}
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css"
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />


<!-- Nucleo Icons -->
<link href="{% static 'css/nucleo-icons.css' %}" rel="stylesheet"/>
<link href="{% static 'css/nucleo-svg.css' %}" rel="stylesheet"/>

<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
<!-- Nepcha Analytics (nepcha.com) -->
<!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
<script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>

<!-- CSS Files -->


<link id="pagestyle" href="{% static 'css/material-dashboard' %}" rel="stylesheet"/>





  {% block title %}
  <!-- <title>Document</title> -->
  {% endblock title %}



</head>


<body class="g-sidenav-show  bg-gray-200">


    {% include 'sidebar.html' %}
    {% block body %}

    {% endblock body %}


</body>

<!--   Core JS Files   -->
<script src="{% static 'js/core/popper.min.js' %}"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/plugins/smooth-scrollbar.min.js' %}"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>


<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'js/material-dashboard.min.js?v=3.1.0' %}"></script>


</html>

src/templates/menu/edit_form.html
{% extends 'base.html' %}
{%load static%}


  <title>
    Liste des plats
  </title>
 
  {% block body %}

<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

    


    <hr class="horizontal light mt-0 mb-2">

    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">


            <li class="nav-item">
                <a class="nav-link text-white " href="menus.html">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">menu_book</span>
                    </div>

                    <span class="nav-link-text ms-1">Menus</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link text-white " href="plats.html">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">local_cafe</span>
                    </div>

                    <span class="nav-link-text ms-1">Plats</span>
                </a>
            </li>

        </ul>
    </div>

</aside>


<main class="main-content  mt-0">
    <section>
        <div class="page-header min-vh-100">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h4 class="font-weight-bolder">Formulaire d'enregistrement</h4>
                            </div>
                            <div class="card-body">
                                <form role="form">
                                    <div class="input-group input-group-outline mb-3">
                                        <label class="form-label">Libelle</label>
                                        <input type="text" class="form-control">
                                    </div>
                                    <div class="input-group input-group-outline mb-3">
                                        <input type="date" class="form-control">
                                    </div>
                                    <div class="text-center">
                                        <button type="button"
                                                class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                            Enregistrer
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock body %}

src/templates/menu/forms.html
{% extends 'base.html' %}

{%load static%}
    


{% block body %}





<main class="main-content  mt-0">
    <section>
        <div class="page-header min-vh-100">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h4 class="font-weight-bolder">Formulaire d'enregistrement</h4>
                            </div>
                            <div class="card-body">
                                <form role="form">
                                    <div class="input-group input-group-outline mb-3">
                                        <label class="form-label">Libelle</label>
                                        <input type="text" class="form-control">
                                    </div>

                                    <div class="input-group input-group-outline mb-3">
                                        <input type="date" class="form-control">
                                    </div>
                                    
                                    <div class="text-center">
                                        <button type="button"
                                                class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                            Enregistrer
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
{% endblock body %}

src/templates/menu/index.html
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="apple-touch-icon" sizes="76x76" href="./assets/img/apple-icon.png">
<link rel="icon" type="image/png" href="./assets/img/favicon.png">

<title>
    Ma cantine scolaire
</title>


<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />


<!-- Nucleo Icons -->
<link href="./assets/css/nucleo-icons.css" rel="stylesheet"/>
<link href="./assets/css/nucleo-svg.css" rel="stylesheet"/>

<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<!-- CSS Files -->


<link id="pagestyle" href="./assets/css/material-dashboard.css?v=3.1.0" rel="stylesheet"/>


<!-- Nepcha Analytics (nepcha.com) -->
<!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
<script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>


</head>


<body class="g-sidenav-show  bg-gray-100">


<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
           aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="index.html"
           target="_blank">
            <img src="./assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
        </a>
    </div>


    <hr class="horizontal light mt-0 mb-2">

    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">


            <li class="nav-item">
                <a class="nav-link text-white " href="pages/menus.html">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">menu_book</span>
                    </div>

                    <span class="nav-link-text ms-1">Menus</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link text-white " href="pages/plats.html">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">local_cafe</span>
                    </div>

                    <span class="nav-link-text ms-1">Plats</span>
                </a>
            </li>

        </ul>
    </div>

</aside>

<main class="main-content border-radius-lg ">


    <div class="container-fluid py-4">

        <footer class="footer py-4  ">
            <div class="container-fluid">
                <div class="row align-items-center justify-content-lg-between">
                    <div class="col-lg-6 mb-lg-0 mb-4">
                        <div class="copyright text-center text-sm text-muted text-lg-start">
                            © <script>
                            document.write(new Date().getFullYear())
                        </script>
                            ADA
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>


</main>


<!--   Core JS Files   -->
<script src="./assets/js/core/popper.min.js"></script>
<script src="./assets/js/core/bootstrap.min.js"></script>
<script src="./assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="./assets/js/plugins/smooth-scrollbar.min.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>


<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="./assets/js/material-dashboard.min.js?v=3.1.0"></script>
</body>

</html>

src/templates/menu/menus.html
{% extends 'base.html' %}
{%load static%}


  <title>
    Liste des menus
  </title>
 
  {% block body %}
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

  





  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <!-- Navbar -->
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
      <div class="container-fluid py-1 px-3">


        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
          <ul class="navbar-nav  justify-content-start">
            <li class="nav-item d-flex align-items-center">
              <a class="btn btn-outline-warning btn-sm mb-0 me-3" href="{% url 'menu:add' %}">Ajouter un menu</a>
            </li>
          </ul>
          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <label class="form-label">Recherche par nom</label>
              <input type="text" class="form-control">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
            <li class="nav-item d-flex align-items-center">
              <button class="btn btn-outline-primary btn-sm mb-0 me-3">Recherche</button>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-warning shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Liste des menus (1)</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Date</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Plat</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2 align-items-center"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">10/11/2024</h6>
                          </div>
                        </div>
                      </td>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">ATTIEKE</h6>
                          </div>
                        </div>
                      </td>
                      <td class="align-middle text-center text-sm">
                        <button class="badge badge-sm bg-gradient-success">Modifier</button>
                        <button class="badge badge-sm bg-gradient-danger">Supprimer</button>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer py-4  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>
                ADA
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </main>
  <!--   Core JS Files   -->
  {% endblock body %}

src/templates/plat/edit_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../assets/img/favicon.png">
    <title>
        Formulaire
    </title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700"/>
    <!-- Nucleo Icons -->
    <link href="../assets/css/nucleo-icons.css" rel="stylesheet"/>
    <link href="../assets/css/nucleo-svg.css" rel="stylesheet"/>
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
    <!-- CSS Files -->
    <link id="pagestyle" href="../assets/css/material-dashboard.css?v=3.1.0" rel="stylesheet"/>
    <!-- Nepcha Analytics (nepcha.com) -->
    <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
    <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
</head>

<body class="g-sidenav-show  bg-gray-200">
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
           aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="../index.html"
           target="_blank">
            <img src="../assets/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
            <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
        </a>
    </div>


    <hr class="horizontal light mt-0 mb-2">

    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">


            <li class="nav-item">
                <a class="nav-link text-white " href="menus.html">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">menu_book</span>
                    </div>

                    <span class="nav-link-text ms-1">Menus</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link text-white " href="plats.html">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">local_cafe</span>
                    </div>

                    <span class="nav-link-text ms-1">Plats</span>
                </a>
            </li>

        </ul>
    </div>

</aside>


<main class="main-content  mt-0">
    <section>
        <div class="page-header min-vh-100">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-12 d-flex flex-column ms-auto me-auto ms-lg-auto me-lg-12">
                        <div class="card card-plain">
                            <div class="card-header">
                                <h4 class="font-weight-bolder">Formulaire d'enregistrement</h4>
                            </div>
                            <div class="card-body">
                                <form role="form">
                                    <div class="input-group input-group-outline mb-3">
                                        <label class="form-label">Libelle</label>
                                        <input type="text" class="form-control">
                                    </div>
                                    <div class="input-group input-group-outline mb-3">
                                        <input type="date" class="form-control">
                                    </div>
                                    <div class="text-center">
                                        <button type="button"
                                                class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
                                            Enregistrer
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<!--   Core JS Files   -->
<script src="../assets/js/core/popper.min.js"></script>
<script src="../assets/js/core/bootstrap.min.js"></script>
<script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
<script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="../assets/js/material-dashboard.min.js?v=3.1.0"></script>
</body>

</html>

src/templates/sidebar.html
{%load static%}


<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark"
       id="sidenav-main">

    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none"
           aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0" href="{ % url 'menu:list' % }"
           target="_blank">
            <span class="ms-1 font-weight-bold text-white">Ma cantine</span>
        </a>
    </div>


    <hr class="horizontal light mt-0 mb-2">

    <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
        <ul class="navbar-nav">


            <li class="nav-item">
                <a class="nav-link text-white " href="{ % url 'menu:list' % }">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">menu_book</span>
                    </div>

                    <span class="nav-link-text ms-1">Menus</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link text-white " href="{ % url 'plat:list' % }">

                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <span class="material-symbols-outlined">local_cafe</span>
                    </div>

                    <span class="nav-link-text ms-1">Plats</span>
                </a>
            </li>
            
        </ul>
    </div>

</aside>